//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS.EInvoiceEasy.Test.ReportGetInvoice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportGetInvoice.IReportGetInvoice")]
    public interface IReportGetInvoice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetOutboundUuidByID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetOutboundUuidByIDResponse")]
        string GetOutboundUuidByID(string VKN, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTr", ReplyAction="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrResponse")]
        byte[] GetOutboundInvoiceAsUblTr(string VKN, string DocumentReferenceNo, string ModulCode, string ID, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByModuleAndReferenc" +
            "e", ReplyAction="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByModuleAndReferenc" +
            "eResponse")]
        byte[] GetOutboundInvoiceAsUblTrByModuleAndReference(string VKN, string DocumentReferenceNo, string ModulCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByUUID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByUUIDResponse")]
        byte[] GetOutboundInvoiceAsUblTrByUUID(string VKN, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetOutboundInvoiceAsUblTrByIDResponse")]
        byte[] GetOutboundInvoiceAsUblTrByID(string VKN, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetInboundUuidByID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetInboundUuidByIDResponse")]
        string GetInboundUuidByID(string VKN, string SupplierVKN, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetInboundUblInvoice", ReplyAction="http://tempuri.org/IReportGetInvoice/GetInboundUblInvoiceResponse")]
        byte[] GetInboundUblInvoice(string VKN, string DocumentReferenceNo, string ModulCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetInboundInvoiceAsUblTrByUUID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetInboundInvoiceAsUblTrByUUIDResponse")]
        byte[] GetInboundInvoiceAsUblTrByUUID(string VKN, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/GetInboundInvoiceAsUblTrByID", ReplyAction="http://tempuri.org/IReportGetInvoice/GetInboundInvoiceAsUblTrByIDResponse")]
        byte[] GetInboundInvoiceAsUblTrByID(string VKN, string SupplierVKN, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGetInvoice/InboundInvoiceAsIsisTr", ReplyAction="http://tempuri.org/IReportGetInvoice/InboundInvoiceAsIsisTrResponse")]
        byte[] InboundInvoiceAsIsisTr(string VKN, string UUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportGetInvoiceChannel : ISIS.EInvoiceEasy.Test.ReportGetInvoice.IReportGetInvoice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportGetInvoiceClient : System.ServiceModel.ClientBase<ISIS.EInvoiceEasy.Test.ReportGetInvoice.IReportGetInvoice>, ISIS.EInvoiceEasy.Test.ReportGetInvoice.IReportGetInvoice {
        
        public ReportGetInvoiceClient() {
        }
        
        public ReportGetInvoiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportGetInvoiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportGetInvoiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportGetInvoiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetOutboundUuidByID(string VKN, string ID) {
            return base.Channel.GetOutboundUuidByID(VKN, ID);
        }
        
        public byte[] GetOutboundInvoiceAsUblTr(string VKN, string DocumentReferenceNo, string ModulCode, string ID, string UUID) {
            return base.Channel.GetOutboundInvoiceAsUblTr(VKN, DocumentReferenceNo, ModulCode, ID, UUID);
        }
        
        public byte[] GetOutboundInvoiceAsUblTrByModuleAndReference(string VKN, string DocumentReferenceNo, string ModulCode) {
            return base.Channel.GetOutboundInvoiceAsUblTrByModuleAndReference(VKN, DocumentReferenceNo, ModulCode);
        }
        
        public byte[] GetOutboundInvoiceAsUblTrByUUID(string VKN, string UUID) {
            return base.Channel.GetOutboundInvoiceAsUblTrByUUID(VKN, UUID);
        }
        
        public byte[] GetOutboundInvoiceAsUblTrByID(string VKN, string ID) {
            return base.Channel.GetOutboundInvoiceAsUblTrByID(VKN, ID);
        }
        
        public string GetInboundUuidByID(string VKN, string SupplierVKN, string ID) {
            return base.Channel.GetInboundUuidByID(VKN, SupplierVKN, ID);
        }
        
        public byte[] GetInboundUblInvoice(string VKN, string DocumentReferenceNo, string ModulCode) {
            return base.Channel.GetInboundUblInvoice(VKN, DocumentReferenceNo, ModulCode);
        }
        
        public byte[] GetInboundInvoiceAsUblTrByUUID(string VKN, string UUID) {
            return base.Channel.GetInboundInvoiceAsUblTrByUUID(VKN, UUID);
        }
        
        public byte[] GetInboundInvoiceAsUblTrByID(string VKN, string SupplierVKN, string ID) {
            return base.Channel.GetInboundInvoiceAsUblTrByID(VKN, SupplierVKN, ID);
        }
        
        public byte[] InboundInvoiceAsIsisTr(string VKN, string UUID) {
            return base.Channel.InboundInvoiceAsIsisTr(VKN, UUID);
        }
    }
}
